# Generated by Django 5.0.6 on 2024-07-04 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('contacto_PK', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('alias', models.CharField(max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('foto_binario', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Correo',
            fields=[
                ('correo_PK', models.IntegerField(primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=254)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correos', to='Contactos.contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('direccion_PK', models.IntegerField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=100)),
                ('numero_exterior', models.CharField(max_length=10)),
                ('colonia', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='Contactos.contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('telefono_PK', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=20)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='Contactos.contacto')),
            ],
        ),
    ]
