# Generated by Django 5.0.6 on 2024-07-06 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contactos', '0002_alter_contacto_contacto_pk_alter_correo_correo_pk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='foto_binario',
        ),
    ]
