# Generated by Django 5.0.6 on 2024-07-06 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contactos', '0003_remove_contacto_foto_binario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='foto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
